### ISSUE TITLE
More information display

### ISSUE THREAD

**Issue by taseikyo** [brainbush/matsuri.icu#1]
既然有弹幕数据，感觉可以画很多图哇
![20210107114644](https://user-images.githubusercontent.com/23132915/103848575-a6b7f400-50dd-11eb-8afc-f4434f85e155.png)
比如在下面可以显示弹幕数量TOP10、发弹幕数量最多的人TOP10之类的
之前有人建议我做 我没服务器（嫌麻烦
偶然发现这个网站，我觉得你可以试试（

**Comment by inkydragon** [comment]
附议

一些 idea
+ 可以统计每分钟的弹幕密度，类似B站视频的高能进度条。可以看见这期的热点片段。
+ 今天可能的同传man
+ 本次直播出现的高频弹幕。图中画的是固定短语的出现次数。但不同直播间、不同的直播内容就可能有不同的高频弹幕。这个只能通过统计获得。

**Comment by brainbush** [comment]
了解
谢谢建议！
先放在这等我有时间再考虑如何进一步完善吧

**Comment by taseikyo** [comment]
期待新功能~

**Comment by brainbush** [comment]
![image](https://user-images.githubusercontent.com/2290026/125800172-514cafd5-f9a8-415f-a3e0-163cce915059.png)
咕咕咕半年大概改了一下

**Comment by taseikyo** [comment]
> ![image](https://user-images.githubusercontent.com/2290026/125800172-514cafd5-f9a8-415f-a3e0-163cce915059.png)
> 咕咕咕半年大概改了一下

好耶！
