### ISSUE TITLE
弹幕热词曲线显示特殊符号

### ISSUE THREAD

**Issue by zhou-zl18** [brainbush/matsuri.icu#10]
我看一些颜文字出现频率很高，但在曲线中没有显示，比如♡v♡
能否加上呢♡v♡

**Comment by brainbush** [comment]
特殊符号不太好处理（其实就是jieba不认的样子）
暂时不考虑
如有好的方案，欢迎对 [解析highlight的脚本](https://github.com/brainbush/api.matsuri.icu/blob/master/highlight.py) 提交pr
