### ISSUE TITLE
/viewer/{mid}  301 跳转

### ISSUE THREAD

**Issue by chanchancl** [brainbush/matsuri.icu#2]
RT
例如 https://matsuri.icu/viewer/49929081
经常301 跳转到NGA的AS专楼

这是BUG吗，还是专门这么写的。。。

**Comment by brainbush** [comment]
![image](https://user-images.githubusercontent.com/2290026/108966055-ae951d00-76b8-11eb-8d71-307ead2a1e43.png)
~~被发现了~~
