### ISSUE TITLE
关于前端viewer页面刷新的问题

### ISSUE THREAD

**Issue by KBdog** [brainbush/matsuri.icu#7]
想问问大佬viewer页面从地址栏进入或直接刷新跳转douban这是怎么实现的，代码渣求解答

**Comment by brainbush** [comment]
https://github.com/brainbush/matsuri.icu/blob/master/public/viewer/404.html

**Comment by KBdog** [comment]
大佬，我想知道为啥会到自定义的404页面，我看了代码没有路由到这个页面的

**Comment by brainbush** [comment]
https://developers.cloudflare.com/pages/platform/serving-pages#not-found-behavior

**Comment by KBdog** [comment]
> https://developers.cloudflare.com/pages/platform/serving-pages#not-found-behavior

好的谢谢大佬
